import:
  - ~/dotfiles/config/alacritty/colors/nord.yml

window:
  padding:
    x: 10
    y: 5
  dynamic_padding: false

  decorations: "none"

font:
  normal:
    family: Liga SFMono Nerd Font
  bold:
    family: Liga SFMono Nerd Font
  italic:
    family: Liga SFMono Nerd Font
  size: 15

key_bindings:
  - { key: Slash,  mods: Control,       chars: ^_ }
  - { key: Slash,  mods: Control|Shift, chars: ^_ }
